version: '2'
services:
  app:
    build: .
    working_dir: /src/app
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app/
    # depends_on:
    #   - db
    environment:
      - DATABASE_HOST=db
  # db:
  #   image: dydx/alpine-mariadb
