version: '3'

services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: docfy
  app:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app/
